CREATE DATABASE IF NOT EXISTS T4_Car_Insurance_DB;

USE T4_Car_Insurance_DB;

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Customer 
(
	CUST_ID VARCHAR(20) PRIMARY KEY,
    CUST_FNAME VARCHAR(10) NOT NULL,
    CUST_LNAME VARCHAR(10) NOT NULL,
    CUST_DOB DATE NOT NULL,
    CUST_GENDER VARCHAR(2) CHECK (CUST_GENDER IN ('M', 'F')),
    CUST_ADDRESS VARCHAR(20) NOT NULL,
    CUST_MOB_NUMBER INT NOT NULL,
    CUST_EMAIL VARCHAR(20) UNIQUE NOT NULL,
    CUST_PASSPORT_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    CUST_MARITAL_STATUS VARCHAR(8) NOT NULL CHECK (CUST_MARITAL_STATUS IN ('Married', 'Single')),
    CUST_PPS_NUMBER INT UNIQUE NOT NULL
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Application
(
	APPLICATION_ID VARCHAR(20) PRIMARY KEY,
    CUST_ID VARCHAR(20),
    VEHICLE_ID VARCHAR(20) NOT NULL, -- ADD THE FOREIGN KEY FOR THIS LATER ----------
    APPLICATION_STATUS VARCHAR(8) NOT NULL CHECK (APPLICATION_STATUS IN ('Pending', 'Rejected', 'Accepted')),
    COVERAGE VARCHAR(50) NOT NULL,
    FOREIGN KEY (CUST_ID) REFERENCES T4_Customer(CUST_ID)
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Quote
(
	QUOTE_ID VARCHAR(20) PRIMARY KEY,
    APPLICATION_ID VARCHAR(20) NOT NULL,
    CUST_ID VARCHAR(20),
    ISSUE_DATE DATE NOT NULL,
    VALID_FROM_DATE DATE NOT NULL,
    VALID_TILL_DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    PRODUCT_ID VARCHAR(20) NOT NULL, -- ADD FOREGN KEY FOR THIS LATER ----------
    COVERAGE_LEVEL VARCHAR(20) NOT NULL,
    FOREIGN KEY (CUST_ID) REFERENCES T4_Customer(CUST_ID),
    FOREIGN KEY (APPLICATION_ID) REFERENCES T4_Application(APPLICATION_ID)
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Premium_Payment
(
	PREMIUM_PAYMENT_ID VARCHAR(20) PRIMARY KEY,
    CUST_ID VARCHAR(20) NOT NULL,
    POLICY_NUMBER VARCHAR(20) NOT NULL,  
    PREMIUM_PAYMENT_SCHEDULE DATE NOT NULL,
    PREMIUM_PAYMENT_AMOUNT INT NOT NULL,
    RECEIPT_ID VARCHAR(20) NOT NULL, -- foreign key to receipt, add later ---------
    
    FOREIGN KEY (CUST_ID) REFERENCES T4_Customer(CUST_ID)
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Claim
(
	CLAIM_ID VARCHAR(20) PRIMARY KEY,
    CUST_ID VARCHAR(20) NOT NULL,
    AGREEMENT_ID VARCHAR(20)NOT NULL, -- ADD THE FOREGN KEY FOR THIS LATER ------------
    CLAIM_AMOUNT INT NOT NULL,
    INCIDENT_ID VARCHAR(20) NOT NULL, -- ADD THE FOREIGN KEY FOR THIS LATER -------------
    DAMAGE_TYPE VARCHAR(20) NOT NULL,
    DATE_OF_CLAIM DATE NOT NULL,
    CLAIM_STATUS VARCHAR(10) NOT NULL,
    
    FOREIGN KEY (CUST_ID) REFERENCES T4_Customer(CUST_ID)
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Claim_Settlement
(
	CLAIM_SETTLEMENT_ID VARCHAR(20) PRIMARY KEY,
    CLAIM_ID VARCHAR(20) NOT NULL,
    CUST_ID VARCHAR(20) NOT NULL,
    VEHICLE_ID VARCHAR(20) NOT NULL, -- ADD FOREIGN KEY FOR THIS LATER ----------
    DATE_SETTLED DATE NOT NULL,
    AMOUNT_PAID INT NOT NULL,
    COVERAGE_ID VARCHAR(20) NOT NULL,
    
    FOREIGN KEY (CUST_ID) REFERENCES T4_Customer(CUST_ID),
    FOREIGN KEY (CLAIM_ID) REFERENCES T4_Claim(CLAIM_ID)
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Coverage
(
    COVERAGE_ID VARCHAR(20) PRIMARY KEY,
    COVERAGE_AMOUNT INT NOT NULL,
    COVERAGE_TYPE VARCHAR(10) NOT NULL,
    COVERAGE_LEVEL VARCHAR(15) NOT NULL CHECK (COVERAGE_LEVEL IN ('HIGH', 'MEDIUM', 'LOW')),
    PRODUCT_ID VARCHAR(20) NOT NULL, -- ADD FOREIGN KEY FOR THIS LATER --------
    COVERAGE_DESCRIPTION VARCHAR(100) NOT NULL,
    COVERAGE_TERMS VARCHAR(50) NOT NULL,
    COMPANY_NAME VARCHAR(20) NOT NULL
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Insurance_policy (
    Agreement_id VARCHAR(20) PRIMARY KEY,
    Application_id VARCHAR(20) NOT NULL, -- ADDING FOREIGN KEY -------
    Cust_id VARCHAR(20) NOT NULL, -- ADDING FOREIGN KEY --------
    Department_name VARCHAR(20) NOT NULL, -- ADDING FOREIGN KEY --------
    Policy_number VARCHAR(20) NOT NULL,
    Start_date DATE NOT NULL,
    Expiry_date DATE NOT NULL,
    Term_condition_description VARCHAR(100) NOT NULL
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Vehicle (
    Vehicle_id VARCHAR(20) PRIMARY KEY,
    Cust_id VARCHAR(20) NOT NULL, -- FOREIGN KEY ------
    Policy_id VARCHAR(20) NOT NULL,
    Dependent_nok_id VARCHAR(20), -- FOREIGN KEY , HAD TO CREATE NEXT OF KIN TABLE -------
    Vehicle_registration_number VARCHAR(20),   -- UNIQUE NOT NULL
    Vehicle_value INT NOT NULL,
    Vehicle_type VARCHAR(20) NOT NULL,
    Vehicle_size INT NOT NULL,
    Vehicle_number_of_seat INT NOT NULL,
    Vehicle_manufacturer VARCHAR(20) NOT NULL,
    Vehicle_engine_number INT UNIQUE NOT NULL,
    Vehicle_chasis_number INT UNIQUE NOT NULL,
    Vehicle_number VARCHAR(20),
    Vehicle_model_number VARCHAR(20) UNIQUE NOT NULL
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Department (
    Department_name VARCHAR(20) PRIMARY KEY,
    Company_name VARCHAR(20) NOT NULL, -- FOREIGN KEY ------
    Office VARCHAR(20) NOT NULL,
    Contact_information VARCHAR(20) UNIQUE NOT NULL,
    Department_staff VARCHAR(50) NOT NULL,
    Department_leader VARCHAR(20) NOT NULL
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Office (
    Office_name VARCHAR(20) PRIMARY KEY,
	Office_leader VARCHAR(20) NOT NULL,
	Contact_information VARCHAR(20) UNIQUE NOT NULL,
	Address VARCHAR(20) NOT NULL,
	Admin_cost INT NOT NULL,
	Staff VARCHAR(50) NOT NULL,
    Department_name VARCHAR(20) NOT NULL, -- FOREIGN KEY ------
    Company_name VARCHAR(20) NOT NULL -- FOREIGN KEY ------
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Vehicle_service (
    Vehicle_service VARCHAR(20) PRIMARY KEY,
    Vehicle_id VARCHAR(20) NOT NULL, -- FOREIGN KEY ----
    Cust_id VARCHAR(20) NOT NULL, -- FOREIGN KEY ----
    Department_name CHAR(20) NOT NULL, -- FOREIGN KEY -----
    Vehicle_service_address VARCHAR(20) NOT NULL,
    Vehicle_service_contact VARCHAR(20) UNIQUE NOT NULL,
    Vehicle_service_incharge CHAR(20) NOT NULL,
    Vehicle_service_type VARCHAR(20) NOT NULL
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Product (
    Product_number VARCHAR(20) PRIMARY KEY,
    Product_price INT NOT NULL,
    Product_type CHAR(15) NOT NULL,
    Company_name VARCHAR(20) NOT NULL -- FOREIGN KEY -----  
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Insurance_company (
    Company_name VARCHAR(20) PRIMARY KEY,
    Company_address VARCHAR(100) NOT NULL,
    Company_contact_number INT UNIQUE NOT NULL,
    Company_fax INT UNIQUE NOT NULL,
    Company_email VARCHAR(50) UNIQUE NOT NULL,
    Company_website VARCHAR(50) NOT NULL,
    Company_location VARCHAR(50) NOT NULL,
    Company_department_name VARCHAR(50) NOT NULL,
    Company_office_name VARCHAR(50) NOT NULL
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Receipt
(
	RECEIPT_ID VARCHAR(20) PRIMARY KEY,
    PREMIUM_PAYMENT_ID VARCHAR(20),  -- NOT NULL
    CUST_ID VARCHAR(20) NOT NULL,
    COST INT NOT NULL,
    TIME DATE NOT NULL,
    
    FOREIGN KEY (CUST_ID) REFERENCES T4_Customer(CUST_ID),
    FOREIGN KEY (PREMIUM_PAYMENT_ID) REFERENCES T4_Premium_Payment(PREMIUM_PAYMENT_ID)
);

CREATE TABLE IF NOT EXISTS T4_Insurance_Policy_Coverage
(
	AGREEMENT_ID VARCHAR(20),
    COVERAGE_ID VARCHAR(20),
    
    PRIMARY KEY (AGREEMENT_ID, COVERAGE_ID),
    FOREIGN KEY (COVERAGE_ID) REFERENCES T4_Coverage(COVERAGE_ID)
);

-- INCIDENT
CREATE TABLE IF NOT EXISTS T4_Incident
(
	INCIDENT_ID VARCHAR(20) PRIMARY KEY,
    INCIDENT_TYPE VARCHAR(30) NOT NULL,
    INCIDENT_DATE DATE NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_Incident_Report
(
	INCIDENT_REPORT_ID VARCHAR(20) PRIMARY KEY,
    INCIDENT_ID VARCHAR(20) NOT NULL, 
    CUST_ID VARCHAR(20) NOT NULL,
    INCIDENT_INSPECTOR VARCHAR(20) NOT NULL,
    INCIDENT_COST INT NOT NULL,
    INCIDENT_TYPE VARCHAR(10) NOT NULL,
    INCIDENT_REPORT_DESCRIPTION VARCHAR(100) NOT NULL,
    
    FOREIGN KEY (INCIDENT_ID) REFERENCES T4_Incident(INCIDENT_ID),
    FOREIGN KEY (CUST_ID) REFERENCES T4_Customer(CUST_ID)
);

-- INSERTED
CREATE TABLE IF NOT EXISTS T4_NOK
(
	NOK_ID VARCHAR(20) PRIMARY KEY,
    AGREEMENT_ID VARCHAR(20) NOT NULL,
    CUST_ID VARCHAR(20) NOT NULL,
    NOK_NAME VARCHAR(20) NOT NULL,
    NOK_ADDRESS VARCHAR(20) NOT NULL,
    NOK_PHONE_NUMBER INT NOT NULL,
    NOK_MARITAL_STATUS VARCHAR(8) NOT NULL CHECK (NOK_MARITAL_STATUS IN ('Married', 'Single')),
    NOK_GENDER VARCHAR(2) NOT NULL CHECK (NOK_GENDER IN ('M', 'F')),
    
    FOREIGN KEY (CUST_ID) REFERENCES T4_Customer(CUST_ID),
    FOREIGN KEY (AGREEMENT_ID) REFERENCES T4_Insurance_Policy(AGREEMENT_ID)
);

ALTER TABLE T4_Application
ADD FOREIGN KEY (VEHICLE_ID) REFERENCES T4_Vehicle(VEHICLE_ID);

ALTER TABLE T4_Quote
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES T4_Product(Product_Number);

ALTER TABLE T4_Premium_Payment
ADD FOREIGN KEY (RECEIPT_ID) REFERENCES T4_Receipt(RECEIPT_ID);

ALTER TABLE T4_Claim
ADD FOREIGN KEY (AGREEMENT_ID) REFERENCES T4_Insurance_Policy(AGREEMENT_ID); 

ALTER TABLE T4_Claim
ADD FOREIGN KEY (INCIDENT_ID) REFERENCES T4_Incident(INCIDENT_ID);

ALTER TABLE T4_CLaim_Settlement
ADD FOREIGN KEY (VEHICLE_ID) REFERENCES T4_Vehicle(VEHICLE_ID);

ALTER TABLE T4_Insurance_Policy
ADD FOREIGN KEY (CUST_ID) REFERENCES T4_Customer(CUST_ID);

ALTER TABLE T4_Insurance_Policy
ADD FOREIGN KEY (DEPARTMENT_NAME) REFERENCES T4_Department(DEPARTMENT_NAME);

ALTER TABLE T4_Insurance_Policy_Coverage
ADD FOREIGN KEY (AGREEMENT_ID) REFERENCES T4_Insurance_Policy(AGREEMENT_ID);

ALTER TABLE T4_Vehicle
ADD FOREIGN KEY (CUST_ID) REFERENCES T4_Customer(CUST_ID);

ALTER TABLE T4_Vehicle
ADD FOREIGN KEY (DEPENDENT_NOK_ID) REFERENCES T4_NOK(NOK_ID);

ALTER TABLE T4_Department
ADD FOREIGN KEY (COMPANY_NAME) REFERENCES T4_Insurance_Company(COMPANY_NAME);

ALTER TABLE T4_Office
ADD FOREIGN KEY (DEPARTMENT_NAME) REFERENCES T4_Department(DEPARTMENT_NAME);

ALTER TABLE T4_Office
ADD FOREIGN KEY (COMPANY_NAME) REFERENCES T4_Insurance_Company(COMPANY_NAME);

ALTER TABLE T4_Vehicle_Service
ADD FOREIGN KEY (CUST_ID) REFERENCES T4_Customer(CUST_ID);

ALTER TABLE T4_Vehicle_Service
ADD FOREIGN KEY (DEPARTMENT_NAME) REFERENCES T4_Department(DEPARTMENT_NAME);

ALTER TABLE T4_Vehicle_Service
ADD FOREIGN KEY (VEHICLE_ID) REFERENCES T4_Vehicle(VEHICLE_ID);

ALTER TABLE T4_Product
ADD FOREIGN KEY (COMPANY_NAME) REFERENCES T4_Insurance_Company(COMPANY_NAME);


-- DROP DATABASE T4_Car_Insurance_DB;




